services:
  - type: web
    name: ccp-chatbot
    runtime: python
    plan: free
    envVars:
      - key: PORT
        value: 10000
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
